<?php
define('V_DOMAIN_PATH_UNSLASHED', (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https":"http").'://'.$_SERVER['HTTP_HOST']);
define('V_DOMAIN_PATH', V_DOMAIN_PATH_UNSLASHED.'/');
define('V_FULL_URL_PATH', V_DOMAIN_PATH_UNSLASHED.$_SERVER['REQUEST_URI']);
define('V_MAIN_FOLDER', 'TRAINER/');
define('V_MAIN_ROOT', $_SERVER['DOCUMENT_ROOT'].'/'.V_MAIN_FOLDER);
define('V_MAIN_FOLDER_PATH', V_DOMAIN_PATH.V_MAIN_FOLDER);
define('V_CORE_FOLDER', 'core/');
define('V_CLASS_FOLDER', 'func/');
define('V_CLASS_PREFIX', 'func.');
define('V_CLASS_ROOT', V_MAIN_ROOT.V_CORE_FOLDER.V_CLASS_FOLDER.V_CLASS_PREFIX);
define('V_CORE_FOLDER_PATH', V_MAIN_FOLDER_PATH.V_CORE_FOLDER);
define('V_THEME_FOLDER', 'theme/');
define('V_THEME_FOLDER_PATH', V_CORE_FOLDER_PATH.V_THEME_FOLDER);
define('V_THEME_HEADER', V_CORE_FOLDER.V_THEME_FOLDER.'header.php');
define('V_THEME_FOOTER', V_CORE_FOLDER.V_THEME_FOLDER.'footer.php');
define('V_PROG_QUERY', 'p');
define('V_PROG_FOLDER', 'prog/');
define('V_PROG_FOLDER_PATH', V_CORE_FOLDER.V_PROG_FOLDER);
define('V_PROG_ROOT', V_MAIN_ROOT.V_PROG_FOLDER_PATH);
define('V_LANG_FOLDER', 'lang/');
define('V_LANG_FOLDER_PATH', V_CORE_FOLDER.V_LANG_FOLDER);
define('V_API_FOLDER', 'api/');
define('V_API_FOLDER_PATH', V_CORE_FOLDER.V_API_FOLDER);
define('V_URLP', '/'.V_MAIN_FOLDER.'?'.V_PROG_QUERY.'=');
define('V_UPLOAD_FOLDER', 'upload/');
define('V_PRODUCTS_PIC_FOLDER', 'products/');
define('V_ALLOWED_PIC_EXTENSIONS', array('jpg', 'jpeg', 'png'));
define('V_UPLOAD_FOLDER_PATH', '/'.V_MAIN_FOLDER.V_UPLOAD_FOLDER);
define('V_INVOICES_XLSX_FOLDER', 'invoices-xlsx/');
define('V_INVOICES_XLSX_PATH', V_UPLOAD_FOLDER_PATH.'invoices-xlsx/');
define('V_MAXIMUM_UPLOAD_FILE_SIZE', 2097152);
define('V_ROWS_PER_PAGE_SELECT2', 30);
define('V_HOMEPAGE', 'dashboard');
define('V_SEARCH_QUERY', 'q');
define('V_MSG_QUERY', 'e');
define('V_ROWS_PER_PAGE_QUERY', 'r');
define('V_ROWS_PER_PAGE_TABLES', 50);
define('V_DEFAULT_LANG', 'AR');
define('V_PAGE_QUERY', 'pg');
define('V_404PAGE', '404');
define('V_SIGNPAGE', 'sign-in');
define('V_API_DO_QUERY', 'do');
define('V_API_AUTH_QUERY', 'auth');
define('V_API_PROG_QUERY', 'p');
define('V_COOKIES_NAME', 'TRAINER-COOKIES');
define('V_ENCRYPTION_KEY', 'iU2dWd#aSdiIUwR;qI^uY2asW0oO');
define('V_DB_CHARSET', 'utf8');
define('V_DB_HOSTNAME', 'localhost');
define('V_DB_USERNAME', 'root');
define('V_DB_PASSWORD', '');
define('V_DB_NAME', 'trainer');
define('V_SELECT2_DIR', 'rtl');
define('V_SELECT2_MINIMUM_INPUT_LENGTH', 2);
define('V_WEB_TITLE', 'Elnukhba Co');
define('V_PROJECT_STARTING_DATE', 2018);
define('V_COMPANY', '<a href="mailto:eemfunc@gmail.com">Muhanad I. Jalil</a>');
define('V_AUTHOR', 'Muhanad I. Jalil');
define('V_COPYRIGHT_TXT', 'with <font color="#FF2222">❤</font>');
define('V_MINIMIZE_STRING_LENGTH', 50);
define('V_COMPANY_NAME', 'مركز التعليم المستمر');
?>